name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use nightly compiler.
      run: |
        rustup default nightly
        rustup component add miri
    - name: Run tests for debug
      run: |
        cargo test -- --test-threads=1
        cargo miri test -- --test-threads=1
        cargo clippy
    - name: Run tests for release
      run: |
        cargo test --release -- --test-threads=1
        cargo miri test --release -- --test-threads=1
        cargo clippy --release
      env:
        RUSTFLAGS: -C debug-assertions=n
